# Generated by Django 3.2.8 on 2022-01-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survivor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survivor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gotReported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported', to='survivor.survivor')),
                ('whoReported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='survivor.survivor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('gotReported', 'whoReported'), name='unique_flag'),
        ),
    ]
